# https://pnpm.io/ja/workspaces
# 管理するフォルダの指定
packages:
  - 'packages/**'
  - 'apps/**'
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  esbuild: true
  protobufjs: true
  re2: true
  sharp: true
  unrs-resolver: true
